spring:
  application:
    name: eventflow
  datasource:
    url: jdbc:postgresql://localhost:5432/eventflow
    username: ${DB_USR}
    password: ${DB_PWD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

